### PR TITLE
Identify keyboard layouts supported by Touch Typing Tutorials

### PR DESCRIPTION
**Pull request by pcalves**
Implemented changed discussed in issue #73. Added a couple of resources and layouts supported by each resource (holding off on flag emojis until GitHub adds support). 🙆

### CODE REVIEW

**Comment by iteles** [comment]
@pcalves Thanks for this, it's a much needed improvement :raised_hands: 

Sorry to be a pain, but your text editor seems to have removed the whitespace at the end of the lines, which is what created line breaks in markdown (we felt these were useful to highlight certain points by putting them on their own line). Would you be able to put that whitespace back in before we merge?

**Comment by pcalves** [comment]
Damn you, iA Writer! I think I caught them all.

**Comment by iteles** [comment]
So great, thanks again for the fantastic suggestion and submitting the PR :blush:

**Comment by pcalves** [comment]
You're welcome! I've been looking to get a bit into OSS and this was a nice simple way to get started before getting into code-related PR and such. 😄

**Comment by iteles** [comment]
@pcalves If you're looking to get into OSS, you might also want to follow along with [24 pull requests](https://github.com/24pullrequests/24pullrequests/) in December :blush:

**Pull request merged**
