### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by rorysedgwick**

### CODE REVIEW

**Comment by nelsonic** [comment]
:+1: glad you made it home safely we miss you...

**Comment by nelsonic** [comment]
rory-boat-selfie

**Comment by nelsonic** [comment]
rory-izzak-breath-holding-comp-clear-water

**Comment by nelsonic** [comment]
rory-water-jump

**Comment by nelsonic** [comment]
rory-top-view-of-bolders-and-water

**Comment by rorysedgwick** [comment]
Wish I was still there!
Loving the photos though

**Comment by nelsonic** [comment]
dwylers-in-the-rock-pool

**Comment by nelsonic** [comment]
rory-izzak-donuts

**Comment by nelsonic** [comment]
dwylers-on-donuts

**Comment by nelsonic** [comment]
rory-ready-to-go-bananas-on-donut

Yeah, there are some decent pics. We're stoked you could make it @rorysedgwick !
Obviously _gutted_ you could not stay a bit longer. but I'm sure your Mum's Birthday is going to be awesome! :+1:

**Comment by nelsonic** [comment]
We :heart: U!
dwyl-boat-selfie

**Comment by nelsonic** [comment]
rory-and-django-pontoon

**Comment by nelsonic** [comment]
presenting-demo-dwyl-geres-summer-2015

Alright, enough, sleep well! :+1:

**Pull request merged**
