### PR TITLE
Add section on the command line

### LINKED ISSUE #148: Add section on the command line
Would it be useful to have a section on the command line in "Web Development Fundamentals", after "How the Internet Works" but before "Markdown"? The goal is to make this compact start-here as self-contained an introduction as possible for someone starting.

### PR DESCRIPTION
**Pull request by YvesMuyaBenda**
Fixes  #148. Adds a section on the command line for the README.

### CODE REVIEW

**Comment by YvesMuyaBenda** [comment]
The only thing I am wondering about is the phrase "we don't recommend you use any terminal themes when you're starting out". Since this repo is for folk starting out, I have tried to keep the links to the absolutely necessary basics.

**Comment by YvesMuyaBenda** [comment]
@iteles I suppose we can put a "further command line learning" subsection. In which case, I would link Wes Bos's [Command Line Power User](https://www.youtube.com/watch?v=rl7PzPAZDyY&list=PLu8EoSxDXHP7tXPJp5ZmUpuT7sFvrswzf) (a course in which he talks about customizing the command line), and below that link https://github.com/dwyl/dev-setup#terminal.

The "further learning" subsection will clearly separate beginner from less beginner content, but it might be useful to stress it, with something like "Once you thoroughly have the basics of the command line, it is time to go for mastery."

That is how I think your idea can be incorporated. Any thoughts @nelsonic?

**Comment by YvesMuyaBenda** [comment]
@iteles I suppose we can put a "further command line learning" subsection. In which case, we might link https://github.com/dwyl/dev-setup#terminal and below that link Wes Bos's Command Line Power User (a customizing the command line course).

That is how I think your idea can be incorporated. Any thoughts @nelsonic?

**Comment by nelsonic** [comment]
@YvesMuyaBenda Sounds GTM! 👍

**Comment by iteles** [comment]
This is great @YvesMuyaBenda, we an always iterate further :blush:

**Comment by YvesMuyaBenda** [comment]
Cool!

**Pull request merged**
