### PR TITLE
Updated README.md broken links

### PR DESCRIPTION
**Pull request by blossomica**
It seems that the link directing to "JavaScript The Good Parts" is broken so I added a new link that works. Let me know if there needs to be any changes. 

Additionally lines 157, 170, 189 have videos that YouTube has terminated, or removed due to copyright claims. I can remove those if you want or you can substitute them with a good equivalent.

### CODE REVIEW

**Comment by nelsonic** [comment]
Oh... thanks for spotting the broken links & *fixing* the **Good Parts** one. @blossomica !

**Comment by nelsonic** [comment]
broken-youtube-links

This is a Problem we are going to *continue* facing until we *Produce* our own video content...

Issues to be resolved:
+ Learn HTML5: https://github.com/dwyl/start-here/issues/68
+ CSS Tutorial for Beginners in 1 Hour: https://github.com/dwyl/start-here/issues/69
+ JavaScript introduction in 1h: https://github.com/dwyl/start-here/issues/70

@markwilliamfirth we're going to need your help on this...

@blossomica please tell us which video you would most like to see us make *first*...

**Comment by blossomica** [comment]
@nelsonic - Do you mean HTML - CSS - JS basics like the broken videos or in general?

**Comment by iteles** [comment]
@blossomica We mean both!

We'll probably start with either HTML, CSS or JS given that they're the foundation for many others but we really want to know what will me most useful to you. :blush:

**Comment by nelsonic** [comment]
I was thinking of going *all* the way *back to basics* with a "What is the Internet?" video ... but that might be too simplistic ...

**Comment by blossomica** [comment]
@iteles and @nelsonic  I think there are many videos stuck on the basics without offering something practical. So after finishing those videos when it comes to a point where you want to create something on your own it becomes very confusing. Instead of a tutorial were the tutor is just reading the code they write I'll like to see where where the tutor speaks of their thought process. Why did they choose this API, how did they came up with the color scheme. One that shows the thought process of a full stack developers so that after following it we can know the thought process that involves in building a project. Risks / Positive etc.  A tutorial series on a product involving full stack programming... front end - back end - data bases - APIs anything possible will be great because usually a lot of free courses are either super beginner or very advanced and have no flow. So in short apart of the basics eventually I will like to see a nice cool full stack project utilizing the things I mentioned above :)

**Comment by nelsonic** [comment]
@blossomica you appear to be reading our minds ... :bulb: 
we will be working on this in the *very* near future: https://github.com/dwyl/video/issues
And we will be needing *plenty* of help to produce and test the content. :+1: 
:star: the repo if you're interested.

**Comment by blossomica** [comment]
@nelsonic - Sounds pretty interesting. It seems like you are on the way to produce high quality videos from the present open issues.

**Comment by blossomica** [comment]
@iteles and @nelsonic - Before I forget, I will also like to see a video series on technical interview preparation especially with emphasis on data structures/algorithm. Because a lot of companies ask for that and it is something I really need to learn but It seems like a very complex subject. It isn't asked in all interviews I guess but at least for software engineering I see it all over the place. It will be nice videos are succinct and either a few or brief sections because when there are really long they are hard to concentrate on after a while and if it long  it can make someone feel they haven't accomplish much because they are just in video 1 from 100 each being 30 min or 1 hour.

**Comment by nelsonic** [comment]
Noted. :+1:

**Comment by iteles** [comment]
@blossomica Could I ask you to put your comments on the videos you'd like to see into an issue so they don't get lost when I merge in this pull request? :blush:

**Comment by blossomica** [comment]
@iteles - Done!

**Comment by iteles** [comment]
@blossomica Thanks! We'll create another PR to solve #68, #69 and #70 :blush:

**Pull request merged**
