### PR TITLE
Added Clean Code to books-to-read

### PR DESCRIPTION
**Pull request by karinakozarova**
Added Clean Code book following the exact format in JSON

### CODE REVIEW

**Comment by iteles** [comment]
Hi @karinakozarova, so glad you found us! 
It's really great to see your enthusiasm here but please read our contributing policy at https://github.com/dwyl/contributing for further contributions - we aim to open an issue before a PR to validate the need and then let someone else peer review and merge our PRs (no matter how small) :blush:

Thanks again for this great contribution!

**Comment by karinakozarova** [comment]
@iteles thanks for the information,will follow it. Sorry for any inconvenience. 😞

**Comment by nelsonic** [comment]
@karinakozarova no need to apologize, you had no way of knowing the "workflow". 👍 
thanks again for your great contribution! 🎉 `

**Comment by iteles** [comment]
@karinakozarova As @nelsonic says, you had no way of knowing, it's a great reminder we need to add a CONTRIBUTING.md file to this repo! 

Thanks again :)

**Pull request merged**
